name: home_app_2
description: "App to manage home affairs."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  intl: any
  package_info: ^2.0.2
  dio: ^5.4.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.2.5
  sqflite: ^2.3.0
  flutter_easyloading: ^3.0.5
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^9.1.0
  internet_connection_checker: ^1.0.0+1
  change_app_package_name: ^1.1.0
  google_fonts: ^5.1.0
  flutter_launcher_icons: ^0.13.1


  flutx:


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/icon.png

dev_dependencies:


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"